version: '3'
services:
  app:
    # main builder app
    build:
      context: .
      args:
        is_testing: 1
    volumes:
      - .:/app
    links:
      - httpecho
    depends_on:
      - httpecho
    environment:
      FEDERALIST_BUILDER_CALLBACK: http://httpecho:8080/delete
      STATUS_CALLBACK: http://httpecho:8080/post
      LOG_CALLBACK: http://httpecho:8080/post

  httpecho:
    # TODO: probably not necessary actually?
    image: solsson/http-echo:latest
    environment:
      PORT: 8080
